---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: project-seeker
  name: project-seeker-service
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: project-seeker
  sessionAffinity: None
  type: LoadBalancer